# fly.toml app configuration file generated for osensa-demo on 2026-07-31T05:26:18Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'osensa-demo'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile'

[deploy]
  strategy = 'immediate'

[env]
  RESTAURANT_BROKER_PORT = '8884'
  RESTAURANT_BROKER_TRANSPORT = 'websockets'
  RESTAURANT_BROKER_USE_TLS = 'true'
  RESTAURANT_BROKER_WS_PATH = '/mqtt'
  RESTAURANT_COOK_MAX_SECONDS = '30'
  RESTAURANT_COOK_MIN_SECONDS = '10'
  RESTAURANT_ENABLE_RESET = 'true'
  RESTAURANT_LOG_FORMAT = 'json'
  RESTAURANT_LOG_LEVEL = 'INFO'
  RESTAURANT_LOG_STATE_SNAPSHOTS = 'true'
  RESTAURANT_TABLE_COUNT = '4'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
